name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Install dependencies
        run: opam install dune alcotest ocamlformat -y

      - name: Build
        run: opam exec -- dune build @check

      - name: Run OCaml tests
        run: opam exec -- dune runtest
        
      - name: Lint OCaml
        run: opam exec -- ocamlformat --enable-outside-detected-project --check **/*.ml **/*.mli


      - name: Run Python tests
        run: python3 test/tests.py
